### ISSUE TITLE
Default logger in new rails 7.1 apps

### ISSUE THREAD

**Issue by saimon-moore** [skaes/logjam_agent#60]
The default `environments/production.rb` created by a new rails 7.1/2 app includes the following code:

```
  config.logger = ActiveSupport::Logger.new(STDOUT)
    .tap  { |logger| logger.formatter = ::Logger::Formatter.new }
    .then { |logger| ActiveSupport::TaggedLogging.new(logger) }
```

This code is incompatible with the latest version of logjam_agent and throws the following error:

```
undefined method set_attribute' for #Logger::Formatter:0x0000ffff800ff840`
```

Not sure what the best course of action is e.g. wether a doc change to warn about this (which appears to be the better option) or something else?

**Comment by skaes** [comment]
Since logjam agent requires the use of the logjam specific logger class, this code generated to set up the rails logger in one of the environment initialization files has always been wrong.

Documenting the setup is certainly a good idea. However, assuming you are also using the XING specific internal gem, its documentation should already contain instructions.

**Comment by saimon-moore** [comment]
Thanks for the quick response Stephan!

Yeah I checked https://source.xing.com/gems/xing-logjam-agent but didn't see any. I can open a doc change there.

**Comment by skaes** [comment]
Don't worry, I'll take care of documenting it.

**Comment by skaes** [comment]
Done.

**Comment by saimon-moore** [comment]
Thanks a lot Stefan!
